In [1]:
%pip install numpy matplotlib pandas scikit-learn seaborn

Requirement already satisfied: numpy in ./Users/mohamed/ds-env/lib/python3.14/site-packages (2.2.0)
Requirement already satisfied: matplotlib in ./Users/mohamed/ds-env/lib/python3.14/site-packages (3.10.8)
Requirement already satisfied: pandas in ./Users/mohamed/ds-env/lib/python3.14/site-packages (2.2.3)
Requirement already satisfied: scikit-learn in ./Users/mohamed/ds-env/lib/python3.14/site-packages (1.6.0)
Requirement already satisfied: seaborn in ./Users/mohamed/ds-env/lib/python3.14/site-packages (0.13.2)
Requirement already satisfied: contourpy>=1.0.1 in ./Users/mohamed/ds-env/lib/python3.14/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in ./Users/mohamed/ds-env/lib/python3.14/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./Users/mohamed/ds-env/lib/python3.14/site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in ./Users/mohamed/ds-env/lib/python3.14/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in ./Users/mohamed/ds-env/lib/python3.14/site-packages (from matplotlib) (26.1)
Requirement already satisfied: pillow>=8 in ./Users/mohamed/ds-env/lib/python3.14/site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in ./Users/mohamed/ds-env/lib/python3.14/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in ./Users/mohamed/ds-env/lib/python3.14/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./Users/mohamed/ds-env/lib/python3.14/site-packages (from pandas) (2026.3.post1)
Requirement already satisfied: tzdata>=2022.7 in ./Users/mohamed/ds-env/lib/python3.14/site-packages (from pandas) (2026.1)
Requirement already satisfied: scipy>=1.6.0 in ./Users/mohamed/ds-env/lib/python3.14/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.2.0 in ./Users/mohamed/ds-env/lib/python3.14/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in ./Users/mohamed/ds-env/lib/python3.14/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in ./Users/mohamed/ds-env/lib/python3.14/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
    roc_auc_score
)

In [20]:
import pandas as pd

df = pd.read_csv("/Users/mohamed/Downloads/weatherAUS.csv")

In [21]:
df.shape

(145460, 23)

In [22]:
df.columns

Index(['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RainTomorrow'],
      dtype='object')

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           145460 non-null  object
 1   Location       145460 non-null  object
 2   MinTemp        143975 non-null  float64
 3   MaxTemp        144199 non-null  float64
 4   Rainfall       142199 non-null  float64
 5   Evaporation    82670 non-null   float64
 6   Sunshine       75625 non-null   float64
 7   WindGustDir    135134 non-null  object
 8   WindGustSpeed  135197 non-null  float64
 9   WindDir9am     134894 non-null  object
 10  WindDir3pm     141232 non-null  object
 11  WindSpeed9am   143693 non-null  float64
 12  WindSpeed3pm   142398 non-null  float64
 13  Humidity9am    142806 non-null  float64
 14  Humidity3pm    140953 non-null  float64
 15  Pressure9am    130395 non-null  float64
 16  Pressure3pm    130432 non-null  float64
 17  Cloud9am       89572 non-null   float64
 18  Cloud3pm       86102 non-null   float64
 19  Temp9am        143693 non-null  float64
 20  Temp3pm        141851 non-null  float64
 21  RainToday      142199 non-null  object
 22  RainTomorrow   142193 non-null  object
dtypes: float64(16), object(7)
memory usage: 25.5+ MB

In [24]:
df.isnull().sum()

Date                 0
Location             0
MinTemp           1485
MaxTemp           1261
Rainfall          3261
Evaporation      62790
Sunshine         69835
WindGustDir      10326
WindGustSpeed    10263
WindDir9am       10566
WindDir3pm        4228
WindSpeed9am      1767
WindSpeed3pm      3062
Humidity9am       2654
Humidity3pm       4507
Pressure9am      15065
Pressure3pm      15028
Cloud9am         55888
Cloud3pm         59358
Temp9am           1767
Temp3pm           3609
RainToday         3261
RainTomorrow      3267
dtype: int64

In [28]:
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Missing Percentage": df.isnull().mean() * 100
})

missing = missing.sort_values(
    by="Missing Percentage",
    ascending=False
)

missing

               Missing Values  Missing Percentage
Sunshine                69835           48.009762
Evaporation             62790           43.166506
Cloud3pm                59358           40.807095
Cloud9am                55888           38.421559
Pressure9am             15065           10.356799
Pressure3pm             15028           10.331363
WindDir9am              10566            7.263853
WindGustDir             10326            7.098859
WindGustSpeed           10263            7.055548
Humidity3pm              4507            3.098446
WindDir3pm               4228            2.906641
Temp3pm                  3609            2.481094
RainTomorrow             3267            2.245978
Rainfall                 3261            2.241853
RainToday                3261            2.241853
WindSpeed3pm             3062            2.105046
Humidity9am              2654            1.824557
Temp9am                  1767            1.214767
WindSpeed9am             1767            1.214767
MinTemp                  1485            1.020899
MaxTemp                  1261            0.866905
Location                    0            0.000000
Date                        0            0.000000

In [29]:
missing = df.isnull().sum()
missing_percentage = df.isnull().mean() * 100

for column in df.columns:
    print(f"{column:20} Missing: {missing[column]:6} | {missing_percentage[column]:6.2f}%")

Date                 Missing:      0 |   0.00%
Location             Missing:      0 |   0.00%
MinTemp              Missing:   1485 |   1.02%
MaxTemp              Missing:   1261 |   0.87%
Rainfall             Missing:   3261 |   2.24%
Evaporation          Missing:  62790 |  43.17%
Sunshine             Missing:  69835 |  48.01%
WindGustDir          Missing:  10326 |   7.10%
WindGustSpeed        Missing:  10263 |   7.06%
WindDir9am           Missing:  10566 |   7.26%
WindDir3pm           Missing:   4228 |   2.91%
WindSpeed9am         Missing:   1767 |   1.21%
WindSpeed3pm         Missing:   3062 |   2.11%
Humidity9am          Missing:   2654 |   1.82%
Humidity3pm          Missing:   4507 |   3.10%
Pressure9am          Missing:  15065 |  10.36%
Pressure3pm          Missing:  15028 |  10.33%
Cloud9am             Missing:  55888 |  38.42%
Cloud3pm             Missing:  59358 |  40.81%
Temp9am              Missing:   1767 |   1.21%
Temp3pm              Missing:   3609 |   2.48%
RainToday            Missing:   3261 |   2.24%
RainTomorrow         Missing:   3267 |   2.25%

In [30]:
df["RainTomorrow"].value_counts()

RainTomorrow
No     110316
Yes     31877
Name: count, dtype: int64

In [31]:
df["RainTomorrow"].value_counts(normalize=True) * 100

RainTomorrow
No     77.581878
Yes    22.418122
Name: proportion, dtype: float64

In [32]:
pd.crosstab(
    df["RainToday"],
    df["RainTomorrow"],
    normalize="index"
) * 100

RainTomorrow         No        Yes
RainToday
No            84.813229  15.186771
Yes           53.594023  46.405977

In [33]:
pd.crosstab(
    df["RainToday"],
    df["RainTomorrow"]
)

RainTomorrow     No    Yes
RainToday
No            92728  16604
Yes           16858  14597

In [26]:
df.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No

In [9]:
df.columns

Index(['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RainTomorrow'],
      dtype='object')

In [11]:
df.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No

In [12]:
df.count()

Date             145460
Location         145460
MinTemp          143975
MaxTemp          144199
Rainfall         142199
Evaporation       82670
Sunshine          75625
WindGustDir      135134
WindGustSpeed    135197
WindDir9am       134894
WindDir3pm       141232
WindSpeed9am     143693
WindSpeed3pm     142398
Humidity9am      142806
Humidity3pm      140953
Pressure9am      130395
Pressure3pm      130432
Cloud9am          89572
Cloud3pm          86102
Temp9am          143693
Temp3pm          141851
RainToday        142199
RainTomorrow     142193
dtype: int64

In [13]:
df = df.dropna()

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 56420 entries, 6049 to 142302
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           56420 non-null  object
 1   Location       56420 non-null  object
 2   MinTemp        56420 non-null  float64
 3   MaxTemp        56420 non-null  float64
 4   Rainfall       56420 non-null  float64
 5   Evaporation    56420 non-null  float64
 6   Sunshine       56420 non-null  float64
 7   WindGustDir    56420 non-null  object
 8   WindGustSpeed  56420 non-null  float64
 9   WindDir9am     56420 non-null  object
 10  WindDir3pm     56420 non-null  object
 11  WindSpeed9am   56420 non-null  float64
 12  WindSpeed3pm   56420 non-null  float64
 13  Humidity9am    56420 non-null  float64
 14  Humidity3pm    56420 non-null  float64
 15  Pressure9am    56420 non-null  float64
 16  Pressure3pm    56420 non-null  float64
 17  Cloud9am       56420 non-null  float64
 18  Cloud3pm       56420 non-null  float64
 19  Temp9am        56420 non-null  float64
 20  Temp3pm        56420 non-null  float64
 21  RainToday      56420 non-null  object
 22  RainTomorrow   56420 non-null  object
dtypes: float64(16), object(7)
memory usage: 10.3+ MB

In [15]:
df.columns

Index(['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RainTomorrow'],
      dtype='object')

In [ ]:
df = df.rename(columns=)

In [16]:
df = df[df.Location.isin(['Melbourne','MelbourneAirport','Watsonia',])]

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7557 entries, 64191 to 80997
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           7557 non-null   object
 1   Location       7557 non-null   object
 2   MinTemp        7557 non-null   float64
 3   MaxTemp        7557 non-null   float64
 4   Rainfall       7557 non-null   float64
 5   Evaporation    7557 non-null   float64
 6   Sunshine       7557 non-null   float64
 7   WindGustDir    7557 non-null   object
 8   WindGustSpeed  7557 non-null   float64
 9   WindDir9am     7557 non-null   object
 10  WindDir3pm     7557 non-null   object
 11  WindSpeed9am   7557 non-null   float64
 12  WindSpeed3pm   7557 non-null   float64
 13  Humidity9am    7557 non-null   float64
 14  Humidity3pm    7557 non-null   float64
 15  Pressure9am    7557 non-null   float64
 16  Pressure3pm    7557 non-null   float64
 17  Cloud9am       7557 non-null   float64
 18  Cloud3pm       7557 non-null   float64
 19  Temp9am        7557 non-null   float64
 20  Temp3pm        7557 non-null   float64
 21  RainToday      7557 non-null   object
 22  RainTomorrow   7557 non-null   object
dtypes: float64(16), object(7)
memory usage: 1.4+ MB